excluded:
  - Pods
  - ExomindTechAssessmentTests
  - ExomindTechAssessmentUITests
disabled_rules:
  - todo
  - identifier_name
line_length: 145
nesting:
  type_level:
    warning: 4
  statement_level:
    warning: 6
type_name:
  excluded:
    - ID
identifier_name:
  excluded:
    - id
    - no